site_name: Studio Templates
site_url: https://caio-skyone.github.io/studio-templates/
theme:
  name: material
  palette:
    scheme: slate
  favicon: img/favicon.svg
  logo: img/logo.svg
plugins:
- roamlinks